# Make sure to check the documentation at https://goreleaser.com
---
before:
  hooks:
    - go mod tidy
builds:
  - binary: myks
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
brews:
  - name: myks
    description: A configuration framework for Kubernetes applications
    folder: Formula
    homepage: https://github.com/mykso/myks
    license: MIT
    commit_author:
      name: Mykso Bot
      email: german.lashevich+mykso-bot@gmail.com
    dependencies:
      - name: git
        type: optional
      - name: helm
        type: optional
      - name: vendir
        type: optional
      - name: ytt
        type: optional
    repository:
      owner: mykso
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_REPO_TOKEN }}"
