# Make sure to check the documentation at https://goreleaser.com
---
before:
  hooks:
    - go mod tidy
builds:
  - binary: myks
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
