---
name: Set up abracadabruh
description: Install abracadabruh
branding:
  icon: package
  color: blue
inputs:
  BRUH_VERSION:
    description: "Version of abracadabruh to install"
    default: "0.0.2"
    required: false
  KBLD_VERSION:
    description: "Version of kbld to install"
    default: "v0.37.0"
    required: false
  YTT_VERSION:
    description: "Version of ytt to install"
    default: "v0.45.0"
    required: false
  VENDIR_VERSION:
    description: "Version of vendir to install"
    default: "v0.33.2"
    required: false
  GITHUB_TOKEN:
    description: "GitHub token to use for downloading releases"
    required: true
  ARCH:
    description: "Architecture to use for downloading releases"
    default: "x86_64" # x86_64 | arm64 | ...
    required: false
runs:
  using: composite
  steps:
    - name: Install dependencies
      uses: carvel-dev/setup-action@v1
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        only: ytt, kbld, vendir
        kbld: ${{ inputs.KBLD_VERSION }}
        ytt: ${{ inputs.YTT_VERSION }}
        vendir: ${{ inputs.VENDIR_VERSION }}
    - name: Install abracadabruh
      shell: bash
      run: |
        curl -fsSL https://github.com/Zebradil/abracadabruh/releases/download/${{ inputs.BRUH_VERSION }}/abracadabruh_${{ inputs.BRUH_VERSION }}_Linux_${{ inputs.ARCH }}.tar.gz \
          | tar -xzf - -C /usr/local/bin bruh
        chmod +x /usr/local/bin/bruh
