# https://taskfile.dev
---
version: "3"

silent: true

vars:
  BIN_NAME: "myks"

tasks:
  default: ${GOTASK_BIN:-task} --list

  go:fmt:
    desc: Format the code
    cmds:
      - goimports-reviser -rm-unused -set-alias -format ./...
      - gofumpt -w .

  go:lint:golangci:
    cmds:
      - golangci-lint run

  go:lint:vet:
    cmds:
      - go vet ./...

  go:lint:sec:
    cmds:
      # G304: Potential file inclusion via variable is a false positive
      - gosec -exclude=G304 ./...

  go:lint:
    desc: Lint the code
    deps:
      - go:lint:golangci
      - go:lint:vet
      - go:lint:sec

  go:build:
    desc: Build the binary
    cmds:
      - mkdir -p bin
      - goreleaser build --snapshot --clean --single-target --output
        bin/{{.BIN_NAME}}

  go:test:
    desc: Test the code
    deps:
      - go:build
    cmds:
      - |
        export PATH="{{.ROOT_DIR}}/bin:$PATH"
        go test -failfast -race ./... {{.CLI_ARGS}}
