#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.secret_name
data:
  username: #@ base64.encode(data.values.username)
  password: #@ base64.encode(data.values.password)
