#@ load("@ytt:data", "data")

#@ appData = data.values.application
#@ envData = data.values.environment
#@ myks = data.values.myks

#@ projName = "env-" + envData.id
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: #@ projName
  namespace: #@ appData.namespace
spec:
  description: #@ "Project for \"{}\" environment".format(envData.id)
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - name: #@ appData.destination.name
      namespace: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"

#@ for app in envData.applications:
#@   name = app.name or app.proto
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: #@ "app-{}-{}".format(envData.id, name)
  namespace: #@ appData.namespace
spec:
  destination:
    name: #@ appData.destination.name
    namespace: #@ name
  project: #@ projName
  source:
    #! path: kubernetes/rendered/envs/phoenix-platform-staging/grafana
    #! TODO: Include myks.rootDir or alike in path.
    #!       It is not done right now because it is not clear how to ensure that
    #!       the path is relative to the repository root.
    path: #@ "{}/{}/{}".format(myks.renderedDir, envData.id, app.name)
    plugin:
      name: argocd-vault-plugin-v1.0.0
    repoURL: #@ myks.gitRepoUrl
    targetRevision: #@ myks.gitRepoBranch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
#@ end
