#@ load("@ytt:data", "data")

#@ ap = data.values.argocd.app
---
#@ name = "app-{}-{}".format(data.values.environment.id, ap.name)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: #@ name
  namespace: #@ data.values.argocd.namespace
  annotations:
    app.kubernetes.io/source: #@ ap.source.repoURL
spec:
  destination: #@ ap.destination
  project: #@ ap.project
  source: #@ ap.source
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
