---
name: Check Links Quickly

"on":
  push:
    branches:
      - main
    paths:
      - .github/workflows/check-links-quickly.yaml
      - docs/**.md
  pull_request:
    paths:
      - .github/workflows/check-links-quickly.yaml
      - docs/**.md

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Restore lychee cache
        id: restore-cache
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Run lychee
        uses: lycheeverse/lychee-action@f796c8b7d468feb9b8c0a46da3fac0af6874d374 # v2.2.0
        with:
          fail: true
          args: "--base . --verbose --no-progress --cache --max-cache-age 3d 'docs/**/*.md'"

      - name: Save lychee cache
        uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        if: always()
        with:
          path: .lycheecache
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
