---
name: Check Links Quickly

"on":
  push:
    branches:
      - main
    paths:
      - .github/workflows/check-links-quickly.yaml
      - docs/**.md
  pull_request:
    paths:
      - .github/workflows/check-links-quickly.yaml
      - docs/**.md

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore lychee cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Run lychee
        uses: lycheeverse/lychee-action@v1.9.1
        with:
          fail: true
          args: "--base . --verbose --no-progress --cache --max-cache-age 3d 'docs/**/*.md'"

      - name: Save lychee cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .lycheecache
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
