---
name: Check Links

"on":
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Every day at 10:27 AM UTC
    # The time is random, don't think about it too much
    - cron: "27 10 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
