name: flow-build

on:
  push:
    branches: ['release-2.0']

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    env:
      image_name: mykso/myks
      platforms: linux/amd64,linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: mykso
          password: ${{ secrets.MYKSO_DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ env.image_name }}
          tags: |
            # set latest tag 
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
