---
name: Release PR from dev to main

"on":
  pull_request:
    branches:
      - main

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Release Test
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        env:
          DEBUG: "semantic-release:*"
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/git
