---
name: Release PR from dev to main

"on":
  pull_request:
    branches:
      - main

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Semantic Release Test
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: ${{ github.head_ref }}
          ci: false
          dry_run: true
          extra_plugins: |
            @semantic-release/git
