name: golangci-lint
on:
  push:
    branches:
      - main
    paths:
      - "main.go"
      - "go.mod"
      - "go.sum"
      - ".goreleaser.yml"
      - "cmd/**"
      - "internal/**"
  pull_request:
    branches:
      - main
    paths:
      - "main.go"
      - "go.mod"
      - "go.sum"
      - ".goreleaser.yml"
      - "cmd/**"
      - "internal/**"
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
