name: 'job-lint'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: golangci/golangci-lint-action@v3
