name: "job-lint"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false
      - name: Install gofumpt
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: mvdan/gofumpt
          tag: v0.5.0
          cache: enable
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check code formatting
        run: |
          gofumpt -l $(git diff --name-only --cached --diff-filter=AM) | tee /dev/stderr | test $(wc -l) -eq 0
      - uses: golangci/golangci-lint-action@v3
