name: 'job-test'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: carvel-dev/setup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          only: ytt, vendir
          vendir: latest
          ytt: latest
      - name: Test
        run: go test -v ./...
      - uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: build --snapshot --rm-dist
